### ISSUE TITLE
Add index operations of associated objects on the queue

### ISSUE THREAD

**Issue by medihack** [bdurand/sunspot_index_queue#2]
Does "Sunspot Index Queue" allow to set another object on the queue to be indexed?
When a model indexes also an association, like:

```
class Project < ActiveRecord::Base
  searchable do
    text :task_names do
      self.tasks.map { |task| task.name }
    end
  end
end
```

and the name of a task is altered

```
task.name = "foobar"
task.save
```

then projects that contains that task are not indexed, why I set up an after_save filter to reindex all projects that task belongs to `task.projects.each { |project| project.index }`. Is it possible to add these index operations also on the queue?

**Comment by bdurand** [comment]
You can keep this same code with sunspot_index_queue. There is no difference in the interface for how you specify records to be indexed. The only difference is that they are enqueued for indexing instead of being indexed immediately.

**Comment by medihack** [comment]
Oh, I totally missed you answer. Thanks, Brian ... your gem will help a lot. Closing this now.
