### ISSUE TITLE
Inconsistent behavior between indexes

### ISSUE THREAD

**Issue by springbok** [bdurand/sunspot_index_queue#3]
Hi,

Firstly thank you for the great gem.

I have a strange problem and I'm not sure what is causing the problem. I am trying to index a document using Solr Cell using Sunspot and my own version of sunspot_cell. Firstly I tested this without using the index queue and got an exception as expected as the document was a Word 95 doc which Tika can not handle:

Solr Response: Internal Server Error - which when looking at the Solr log tells me it's Word 95 so all good.

I then wanted to check how the index queue would handle this error, when running the process it looked like everything worked as the entry was deleted from the queue. On checking the Solr log I see that the error was generated and trapped the first time when processing as a batch (in batch.rb), but when it processed it individually no error was generated...strange.

When I run the index without the queue multiple times it always gives me the exception which is what I would have expected from the index queue as well, but this is not the case. Solr seems to respond differently to the second request, I show the section of the Solr log below:
- First Index
  
  09/03/2011 7:33:00 PM org.apache.solr.update.processor.LogUpdateProcessor finish
  INFO: {} 0 2
  09/03/2011 7:33:00 PM org.apache.solr.common.SolrException log
  SEVERE: org.apache.solr.common.SolrException: org.apache.tika.exception.TikaException: Unexpected RuntimeException from org.apache.tika.parser.microsoft.OfficeParser@1176e5f
      at org.apache.solr.handler.extraction.ExtractingDocumentLoader.load(ExtractingDocumentLoader.java:215)
      at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:54)
      at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
      at org.apache.solr.core.RequestHandlers$LazyRequestHandlerWrapper.handleRequest(RequestHandlers.java:233)
      at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
      at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:338)
      at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:241)
      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
      at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:849)
      at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
      at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:454)
      at java.lang.Thread.run(Thread.java:662)
  Caused by: org.apache.tika.exception.TikaException: Unexpected RuntimeException from org.apache.tika.parser.microsoft.OfficeParser@1176e5f
      at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:144)
      at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:99)
      at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:112)
      at org.apache.solr.handler.extraction.ExtractingDocumentLoader.load(ExtractingDocumentLoader.java:194)
      ... 18 more
  Caused by: java.lang.IllegalStateException: Table Stream '0Table' wasn't found - Either the document is corrupt, or is Word95 (or earlier)
      at org.apache.poi.hwpf.HWPFDocument.<init>(HWPFDocument.java:201)
      at org.apache.poi.hwpf.HWPFDocument.<init>(HWPFDocument.java:157)
      at org.apache.poi.hwpf.extractor.WordExtractor.<init>(WordExtractor.java:62)
      at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:95)
      at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:142)
      ... 21 more
- Second index
  
  09/03/2011 7:33:00 PM org.apache.solr.core.SolrCore execute
  INFO: [] webapp=/solr path=/update/extract params={fmap.content=document_attachment_attachment&literal.candidate_ids_im=1&uprefix=ignored_&literal.id=Document+2&literal.type=Document&literal.type=ActiveRecord::Base&literal.document_file_name_texts=Resume+walid+Saleh.doc&idx.attr=false&literal.class_name=Document&wt=ruby&literal.communication_ids_im=2} status=500 QTime=2 
  09/03/2011 7:33:01 PM org.apache.solr.update.DirectUpdateHandler2 commit
  INFO: start commit(optimize=false,waitFlush=false,waitSearcher=true,expungeDeletes=false)
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher <init>
  INFO: Opening Searcher@1580757 main
  09/03/2011 7:33:01 PM org.apache.solr.update.DirectUpdateHandler2 commit
  INFO: end_commit_flush
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher warm
  INFO: autowarming Searcher@1580757 main from Searcher@1074938 main
      fieldValueCache{lookups=0,hits=0,hitratio=0.00,inserts=0,evictions=0,size=0,warmupTime=0,cumulative_lookups=0,cumulative_hits=0,cumulative_hitratio=0.00,cumulative_inse
  rts=0,cumulative_evictions=0}
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher warm
  INFO: autowarming result for Searcher@1580757 main
      fieldValueCache{lookups=0,hits=0,hitratio=0.00,inserts=0,evictions=0,size=0,warmupTime=0,cumulative_lookups=0,cumulative_hits=0,cumulative_hitratio=0.00,cumulative_inserts=0,cumulative_evictions=0}
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher warm
  INFO: autowarming Searcher@1580757 main from Searcher@1074938 main
      filterCache{lookups=0,hits=0,hitratio=0.00,inserts=0,evictions=0,size=0,warmupTime=0,cumulative_lookups=0,cumulative_hits=0,cumulative_hitratio=0.00,cumulative_inserts=0,cumulative_evictions=0}
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher warm
  INFO: autowarming result for Searcher@1580757 main
      filterCache{lookups=0,hits=0,hitratio=0.00,inserts=0,evictions=0,size=0,warmupTime=0,cumulative_lookups=0,cumulative_hits=0,cumulative_hitratio=0.00,cumulative_inserts=0,cumulative_evictions=0}
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher warm
  INFO: autowarming Searcher@1580757 main from Searcher@1074938 main
      queryResultCache{lookups=0,hits=0,hitratio=0.00,inserts=0,evictions=0,size=0,warmupTime=0,cumulative_lookups=24,cumulative_hits=2,cumulative_hitratio=0.08,cumulative_inserts=22,cumulative_evictions=0}
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher warm
  INFO: autowarming result for Searcher@1580757 main
      queryResultCache{lookups=0,hits=0,hitratio=0.00,inserts=0,evictions=0,size=0,warmupTime=0,cumulative_lookups=24,cumulative_hits=2,cumulative_hitratio=0.08,cumulative_inserts=22,cumulative_evictions=0}
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher warm
  INFO: autowarming Searcher@1580757 main from Searcher@1074938 main
      documentCache{lookups=0,hits=0,hitratio=0.00,inserts=0,evictions=0,size=0,warmupTime=0,cumulative_lookups=147,cumulative_hits=99,cumulative_hitratio=0.67,cumulative_inserts=48,cumulative_evictions=0}
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher warm
  INFO: autowarming result for Searcher@1580757 main
      documentCache{lookups=0,hits=0,hitratio=0.00,inserts=0,evictions=0,size=0,warmupTime=0,cumulative_lookups=147,cumulative_hits=99,cumulative_hitratio=0.67,cumulative_inserts=48,cumulative_evictions=0}
  09/03/2011 7:33:01 PM org.apache.solr.core.QuerySenderListener newSearcher
  INFO: QuerySenderListener sending requests to Searcher@1580757 main
  09/03/2011 7:33:01 PM org.apache.solr.core.QuerySenderListener newSearcher
  INFO: QuerySenderListener done.
  09/03/2011 7:33:01 PM org.apache.solr.core.SolrCore registerSearcher
  INFO: [] Registered new searcher Searcher@1580757 main
  09/03/2011 7:33:01 PM org.apache.solr.search.SolrIndexSearcher close
  INFO: Closing Searcher@1074938 main
      fieldValueCache{lookups=0,hits=0,hitratio=0.00,inserts=0,evictions=0,size=0,warmupTime=0,cumulative_lookups=0,cumulative_hits=0,cumulative_hitratio=0.00,cumulative_inserts=0,cumulative_evictions=0}
  09/03/2011 7:33:01 PM org.apache.solr.update.processor.LogUpdateProcessor finish
  INFO: {commit=} 0 7
  09/03/2011 7:33:01 PM org.apache.solr.core.SolrCore execute
  INFO: [] webapp=/solr path=/update params={wt=ruby} status=0 QTime=7 

I'm not sure if the issue is with Solr or the index queue, it seems to be with the index queue as when I run without it and index directly the error and log is always the same.

Any help appreciated,

Etienne.

**Comment by bdurand** [comment]
Could you capture the exceptions in the spot where they are being caught in batch.rb (lines 34, 41, 67, and 81) with something like:

```
 ...
rescue Exception => e
  # Debug exception to STDERR
  STDERR.puts("#{e.inspect}\n#{e.backtrace.join("\n")}"
 ...
```

That might help in starting an investigation.

**Comment by springbok** [comment]
I've spent some time today to dig into this a bit further, turns out there were a couple of issues:

In sunspot indexer.rb we have the following code:

```
def flush_batch
  add_documents(@batch)
  @batch = nil
end
```

If an exception occur @batch is never set to nil, so when the exception occurred it was still being treated as a batch even though sunspot_index_queue was trying treating each entry individually, so in sunspot indexer.rb we have:

   def add(model)
      documents = Util.Array(model).map { |m| prepare(m) }
      if @batch.nil?
        add_documents(documents)
      else
        @batch.concat(documents)
      end
    end

On the second attempt @batch(due to the exception) was not nil so it did a .concat not an add_documents which meant it was being sent out as an update rather than as an extract. In my sunspot_cell code I override the add_documents method to send an extract command to solr, i.e.

```
    def add_documents(documents)
      documents_arr = Sunspot::Util.Array(documents)
      docs_attach = []
      docs_no_attach = []
      documents_arr.each do |document|
        if document.contains_attachment?
          docs_attach << document
        else
          docs_no_attach << document
        end
      end

      unless docs_no_attach.empty?
        @connection.add(docs_no_attach)
      else
        begin
          Sunspot::Util.Array(docs_attach).each do |document|
            document.add(@connection)
          end
        rescue Exception => e
          @batch = nil
          raise
        end
      end
    end
```

To get this to work I added an exception block which sets @batch = nil. Not sure if this is ok as I'm not all that familiar with sunspot internals but is does fix the problem when sunspot_index_queue tries to send entries individually the second time after the first exception it is now NOT treated as an existing batch and the second exception is correctly generated when the extract is sent to Solr. 

My next problem was that after the second exception sunspot_index_queue was still not processing the error correctly, in the following method:

```
  def submit_each_entry
    entries.each do |entry|
      submit_entry(entry)
    end

    begin
      commit!
    rescue Exception => e
      if PASS_THROUGH_EXCEPTIONS.include?(e.class)
        raise e
      else
        entries.each do |entry|
          entry.set_error!(e, @queue.retry_interval)
        end
      end
    end
  end
```

After an exception occurs commit! is still executed and the entry deleted as if it was successful which it was not. Again I may be wrong here but to fix the problem I added a raise e to the following method:

```
  # Update an entry with an error message if a block fails.
  def log_entry_error (entry)
    begin
      yield
      entry.processed = true
      @delete_entries << entry
    rescue Exception => e
      if PASS_THROUGH_EXCEPTIONS.include?(e.class)
        raise e
      else
        entry.set_error!(e, @queue.retry_interval)
        raise e
      end
    end
  end
end
```

Now on error it logs the error and re-raises the exception which then cascades up. The error is now correctly logged in the DB record and not processed.

Sorry for the long winded post I hope it all makes sense. As I said I'm not familiar with the internals of both gems so my modifications may have other implications....

Regards,

Etienne.

**Comment by springbok** [comment]
Sorry I meant to add the comment only not comment and close the issue.

**Comment by springbok** [comment]
It looks like my change causes the daemon script to exit as the exception is passed to it. I don't have time to look at it tonight, I might have a look at tomorrow unless you are able to suggest a solution to quietly handle the exception, log it to the DB and prevent the commit! from happening.

**Comment by springbok** [comment]
Take 2, I've done some more analysis and the problem is caused here:

```
  # Update an entry with an error message if a block fails.
  def log_entry_error (entry)
    begin
      yield
      entry.processed = true
      @delete_entries << entry
    rescue Exception => e
      if PASS_THROUGH_EXCEPTIONS.include?(e.class)
        raise e
      else
        entry.set_error!(e, @queue.retry_interval)
      end
    end
  end
```

The first time all entries are processed as a batch so when this method is executed each entry is added to the @delete_entries array as at this point nothing has been sent to Solr so no exception has occurred.

Once all the entries have been processed the batch is closed and entries flushed to Solr. It's at this point the exception is raised. Entries are then processed one at a time and the above method is called again for each entry. The exception is raised and an error is added to the DB for the entry, all good so far. The problem is that the entry still exists in the @delete_entries array from the first pass. When the commit! is hit in this method:

```
  def submit_each_entry
    entries.each do |entry|
      submit_entry(entry)
    end

    begin
      commit!
    rescue Exception => e
      if PASS_THROUGH_EXCEPTIONS.include?(e.class)
        raise e
      else
        entries.each do |entry|
          entry.set_error!(e, @queue.retry_interval)
        end
      end
    end
  end
```

The entry is deleted even though it has an error and should not be deleted. I added extra code to clear the @delete_entries array before processing the entries individually to fix this problem. Now any problem entries will not be added to the array and therefore not get deleted:

```
  def submit!
    Entry.load_all_records(entries)
    clear_processed(entries)
    begin
      # First try submitting the entries in a batch since that's the most efficient.
      # If there are errors, try each entry individually in case there's a bad document.
      session.batch do
        entries.each do |entry|
          submit_entry(entry)
        end
      end
      commit!
    rescue Exception => e
      if PASS_THROUGH_EXCEPTIONS.include?(e.class)
        raise e
      else
        @delete_entries = []
        submit_each_entry
      end
    end
  rescue Exception => e
    begin
      clear_processed(entries)
      entries.each{|entry| entry.reset!} if PASS_THROUGH_EXCEPTIONS.include?(e.class)
    ensure
      # Use a more specific error to indicate Solr is down.
      e = SolrNotResponding.new(e.message) if e.is_a?(Errno::ECONNREFUSED)
      raise e
    end
  end
```

Regards,

Etienne,

**Comment by bdurand** [comment]
This change has been applied to the latest release

**Comment by swalterd** [comment]
I ran into this issue with batch failing also.  It should be noted that the issue with the batch inside Sunspot being open after the batch add fails still exists unless you override the Sunspot code.
